name: Update Pacman Graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-graph:
    name: Generate and Update Pacman Graph
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create output directory if it doesn't exist
        run: mkdir -p output

      - name: Generate Pacman Graph
        run: |
          curl -s "https://github-stats.jstrieb.dev/api?user=Engel-s&theme=auto&format=svg" > output/pacman-contribution-graph.svg
          curl -s "https://github-stats.jstrieb.dev/api?user=Engel-s&theme=dark&format=svg" > output/pacman-contribution-graph-dark.svg

      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add output/
          git commit -m "Update pacman graphs" || echo "No changes to commit"
          git push
