name: Update Pacman Graph

on:
  schedule:
    - cron: "0 0 * * *" # Ejecuta diariamente a medianoche
  workflow_dispatch: # Permite ejecución manual

jobs:
  update-graph:
    name: Update Pacman Graph
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Pacman Graph
        uses: jstrieb/github-stats@master
        with:
          username: Engel-s
          output_file: output/pacman-contribution-graph.svg
          theme: auto  # Para generar ambos temas claro/oscuro

      - name: Generate Dark Theme Pacman Graph
        uses: jstrieb/github-stats@master
        with:
          username: Engel-s
          output_file: output/pacman-contribution-graph-dark.svg
          theme: dark

      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add output/
          git commit -m "Update pacman graphs" || echo "No changes to commit"
          git push
